name: circles
description: An OS for people migrating from Windows that do not know much about computers

base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest

modules:
  - type: rpm-ostree
    repos: []
    install:
      - wine
      - waydroid
      - ffmpeg
      #extraction
      - unzip
      - p7zip
      - p7zip-plugins
      - unrar
    remove:
      #removes immutable files
      - konsole5
      - dolphin
      - kmail
      - akregator
      - konversation
      - elisa-player
      - dragon

  #adds mutable files
  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - org.kde.dolphin
          - org.kde.konsole
          - org.kde.ark
          - com.vivaldi.Vivaldi
          - com.github.tchx84.Flatseal

  - type: files
    urls: {}
